all: clean install build test docker_build docker_test


install:
	@pip install cookiecutter


build:
	@cookiecutter --no-input https://github.com/rednafi/fastapi-nano.git
	@pip install -r fastapi-nano/requirements.txt
	@pip install -r fastapi-nano/requirements-dev.txt

test:
	@pytest fastapi-nano

clean:
	@rm -rf fastapi-nano


docker_build:
	cd fastapi-nano && docker-compose up -d

docker_test:
	@curl -X GET "http://localhost:5000/api_b/22" -H "accept: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1YnVudHUiLCJleHAiOjY4NTA4OTczNTJ9.2L7NQKiINLo7_O7z8eAZekK40wHBZpNo3q5C0gm47Wo"
