
name: Run unit tests

on:
  push:

  pull_request:
    branches:
      - master

  schedule:
    # Every sunday at 8:05 UTC
    - cron: "5 8 * * 0"

# If you trigger a new workflow while the previous one is running,
# this will cancel the previous one.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      # Use matrix strategy to run the tests on multiple Py versions on multiple OSs.
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the Dependencies
        run: |
          echo "Installing the dependencies..."
          uv sync

      - name: Check Linter
        run: |
          echo "Checking linter formatting..."
          make lint-check

      - name: Run Tests
        run: |
          echo "Running the tests..."
          make test
